### ISSUE TITLE
Updating docs for v0.2

### ISSUE THREAD

**Issue by Dav2070** [drish/resend-ruby#2]
Hey, I was just trying out Resend and started with installing v0.1 of this gem, as the docs suggest. I was confused when I got an error with Spring when running my Rails app after installing the gem, until I discovered v0.2, which fixes this issue.

I suggest to update the readme on this project and the [Resend docs](https://resend.com/docs/send-email-using-rails#install) to point to v0.2, so new users won't have to deal with this issue.

**Comment by drish** [comment]
hey @Dav2070 thanks for pointing that out ! fixed the docs here, will ping the guys over at Resend to update on their side.
